---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/login":
    post:
      summary: Authenticate user and returns a access token
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: valid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_at:
                    type: string
                    format: date_time
                required:
                - access_token
                - expires_at
        '401':
          description: invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: '123123'
              required:
              - email
              - password
  "/api/v1/tasks":
    get:
      summary: List user tasks
      tags:
      - Tasks
      security:
      - bearerAuth: []
      responses:
        '200':
          description: list tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                    due_date:
                      type: string
                      format: date_time
                    user_id:
                      type: integer
                  required:
                  - id
                  - title
                  - description
                  - status
                  - due_date
                  - user_id
servers:
- url: http://localhost:3000
